/* eslint import/order: 0, import/no-unresolved: 0 */

import { Navbar } from 'components/organisms/NavBar'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { getContract } from 'util/getContract'
import styles from '../styles/Home.module.css'
import Artifact from "@cont/ArchiveCoin.json";
import Artifact2 from "@cont/NftContract.json";
import contractAddress from "@cont/contract-address.json";
import { ethers } from 'ethers'

const Home: NextPage = () => {
  async function clickFunc(){
    const contract = await getContract(contractAddress, Artifact);
    const transaction = await contract.createNftContract(ethers.utils.parseEther("0.0001"), {
      value: ethers.utils.parseEther("0.0001"),
    });
    console.log(transaction);
  }
  async function clickFunc2(){
    let provider = new ethers.providers.Web3Provider(window.ethereum);
    const address = provider.getTransactionReceipt("0x862c2fab8b020f831d52e36d15310078eb20f10e20cd09bb756b3f02694fd234").then(function(transactionReceipt) {
      console.log(transactionReceipt);
//       var receipt = web3.eth.getTransactionReceipt('0x94543f3fed0c1a8cc7db88f8b36aa9573b3d9789a2e90f5aeae6a31941a9fe94')
// .then(console.log);
  });
  }
  async function clickFunc3(address: string){
    const contract = await getContract({
      "address": address
    }, Artifact2);
    await contract.safeMint("aaa", {
      value: ethers.utils.parseEther("0.0001"),
    });
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <button className="btn btn-primary">Hello daisyUI</button>
      <button className="btn btn-primary" onClick={()=>clickFunc()}>CreateNftContranct</button>
      <button className="btn btn-primary" onClick={()=>clickFunc2()}>getAddress</button>
      <button className="btn btn-primary" onClick={()=>clickFunc3("0xfd52567785DB542Bf47d1647AB1f0AF8d814211B")}>safemint</button>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
